name: yotei
description: Yotei is a shutdown scheduler utility cross-platform software made in Dart language, currently experimental. Yotei is licensed under the Apache-2.0 license, please read it carefully.
version: 0.6.3
repository: https://github.com/GuilhermeIsNotUnix/Yotei

environment:
  sdk: ^3.11.6

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
